version: '3.8'
services:
  pg-14:
    image: docker.io/library/postgres:14-alpine
    environment: &pg_password
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - PGUSER=postgres
    ports: [50014:5432] # use ports in the ephemeral range
  pg-13:
    image: docker.io/library/postgres:13-alpine
    ports: [50013:5432]
    environment: *pg_password
  pg-12:
    image: docker.io/library/postgres:12-alpine
    ports: [ 50012:5432 ]
    environment: *pg_password
  pg-11:
    image: docker.io/library/postgres:11-alpine
    ports: [ 50011:5432 ]
    environment: *pg_password
  pg-10:
    image: docker.io/library/postgres:11-alpine
    ports: [ 50010:5432 ]
    environment: *pg_password