# .github/workflows/ci.yml

name: Scrape

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_scrape:
    env: { CARGO_TERM_COLOR: always }
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: cache cargo
      uses: Swatinem/rust-cache@v1
    # - uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry/index/
    #       ~/.cargo/registry/cache/
    #       ~/.cargo/git/db/
    #       target/
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: save binary
      uses: actions/upload-artifact@v2
      with:
        name: test-corpus database
        path: ./target/release/splitter