# .github/workflows/ci.yml

name: Scrape

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_splitter:
    env: { CARGO_TERM_COLOR: always }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: cache cargo
        uses: Swatinem/rust-cache@v1
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: save binary
        uses: actions/upload-artifact@v2
        with:
          name: splitter
          path: ./target/release/splitter
  build_predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.17
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build
        run: make bin/predict
      - name: save binary
        uses: actions/upload-artifact@v2
        with:
          name: predict
          path: bin/predict
  assemble_pg_docs:
    runs-on: ubuntu-latest
    needs: [build_splitter]
    steps:
      - uses: actions/checkout@v2
      - name: grab splitter binary
        uses: actions/download-artifact@v2
        with:
          name: splitter
          path: bin
      - run: chmod +x ./bin/splitter && ./bin/splitter --help
      - name: assemble
        run: make /tmp/corpus.db
      - name: save db
        uses: actions/upload-artifact@v2
        with:
          name: pg_regression_corpus
          path: /tmp/corpus.db